# Generated by Django 4.2.17 on 2025-09-19 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="主键"
                    ),
                ),
                (
                    "title",
                    models.CharField(default=" ", max_length=100, verbose_name="标题"),
                ),
                ("summary", models.TextField(default=" ", verbose_name="摘要")),
                ("recovery", models.TextField(default=" ", verbose_name="复现步骤")),
                ("precondition", models.TextField(default=" ", verbose_name="前置条件")),
                ("step", models.TextField(default=" ", verbose_name="操作步骤")),
                (
                    "expect",
                    models.TextField(default=" ", max_length=200, verbose_name="预期结果"),
                ),
                (
                    "actual",
                    models.TextField(default=" ", max_length=200, verbose_name="实际结果"),
                ),
                (
                    "repro",
                    models.CharField(default=" ", max_length=100, verbose_name="复现概率"),
                ),
                ("config", models.TextField(default=" ", verbose_name="配置信息")),
                (
                    "bt_address",
                    models.TextField(default=" ", max_length=100, verbose_name="蓝牙地址"),
                ),
                ("regression", models.TextField(default=" ", verbose_name="回归测试")),
                (
                    "note",
                    models.TextField(default=" ", max_length=200, verbose_name="备注"),
                ),
                (
                    "timestamp",
                    models.TextField(default=" ", max_length=100, verbose_name="时间戳"),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="提交日期"
                    ),
                ),
                (
                    "test_type",
                    models.IntegerField(
                        choices=[
                            (1, "Web"),
                            (2, "App"),
                            (3, "PC"),
                            (4, "接口"),
                            (5, "功能"),
                            (6, "性能"),
                            (7, "安全"),
                            (8, "硬件"),
                            (9, "音频"),
                            (10, "其它"),
                        ],
                        default=1,
                        verbose_name="测试类型",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue_reported_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交人",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issue_reviewed_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评审人",
                    ),
                ),
            ],
            options={
                "verbose_name": "缺陷管理平台",
                "verbose_name_plural": "缺陷管理平台",
                "db_table": "issue_manage_plt_project",
            },
        ),
    ]
