# Generated by Django 4.2.17 on 2025-09-19 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issue_manage_plt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="主键"
                    ),
                ),
                ("join_date", models.DateField(verbose_name="加入日期")),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (1, "测试工程师"),
                            (2, "测试组长"),
                            (3, "测试经理"),
                            (4, "开发工程师"),
                            (5, "运维工程师"),
                            (6, "项目经理"),
                        ],
                        verbose_name="角色",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="状态")),
                ("quit_date", models.DateField(verbose_name="退出日期")),
                (
                    "memo",
                    models.TextField(
                        blank=True,
                        default=" ",
                        max_length=200,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="issue_manage_plt.project",
                        verbose_name="测试项目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目成员",
                "verbose_name_plural": "项目成员",
            },
        ),
    ]
