# Generated by Django 4.2.17 on 2025-09-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue_manage_plt", "0002_projectmember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmember",
            name="quit_date",
            field=models.DateField(blank=True, null=True, verbose_name="退出日期"),
        ),
    ]
