# Generated by Django 4.2.17 on 2025-09-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issue_manage_plt", "0004_alter_projectmember_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="actual",
            field=models.TextField(default=" ", verbose_name="实际结果"),
        ),
        migrations.AlterField(
            model_name="project",
            name="bt_address",
            field=models.TextField(default=" ", verbose_name="蓝牙地址"),
        ),
        migrations.AlterField(
            model_name="project",
            name="config",
            field=models.TextField(default="", verbose_name="配置信息"),
        ),
        migrations.AlterField(
            model_name="project",
            name="expect",
            field=models.TextField(default=" ", verbose_name="预期结果"),
        ),
        migrations.AlterField(
            model_name="project",
            name="note",
            field=models.TextField(default=" ", verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="project",
            name="precondition",
            field=models.TextField(default="", verbose_name="前置条件"),
        ),
        migrations.AlterField(
            model_name="project",
            name="recovery",
            field=models.TextField(default="", verbose_name="复现步骤"),
        ),
        migrations.AlterField(
            model_name="project",
            name="repro",
            field=models.TextField(default=" ", verbose_name="复现概率"),
        ),
        migrations.AlterField(
            model_name="project",
            name="summary",
            field=models.TextField(default="", verbose_name="摘要"),
        ),
        migrations.AlterField(
            model_name="project",
            name="timestamp",
            field=models.TextField(default=" ", verbose_name="时间戳"),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.TextField(default=" ", verbose_name="标题"),
        ),
        migrations.DeleteModel(
            name="ProjectMember",
        ),
    ]
