# Generated by Django 4.2.17 on 2025-09-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, verbose_name="测试项目")),
            ],
            options={
                "verbose_name": "自动化测试",
                "verbose_name_plural": "自动化测试项目",
            },
        ),
    ]
