# Generated by Django 4.2.17 on 2025-09-19 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auto_test_plt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="create_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="describe",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="项目描述"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.BooleanField(default=True, verbose_name="项目状态"),
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Web"),
                    (2, "App"),
                    (3, "PC"),
                    (4, "接口"),
                    (5, "功能"),
                    (6, "性能"),
                    (7, "安全"),
                    (8, "硬件"),
                    (9, "音频"),
                    (10, "其它"),
                ],
                default=1,
                verbose_name="项目类型",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
        ),
        migrations.AddField(
            model_name="project",
            name="version",
            field=models.CharField(default="1.0", max_length=100, verbose_name="项目版本"),
        ),
    ]
