# Generated by Django 4.2.17 on 2025-09-19 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auto_test_plt", "0003_alter_project_options_projectmember"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeployEnv",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="主键"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="环境名称")),
                (
                    "hostname",
                    models.CharField(
                        help_text="IP地址或域名", max_length=100, verbose_name="主机名"
                    ),
                ),
                ("port", models.IntegerField(default=22, verbose_name="端口")),
                ("status", models.BooleanField(default=True, verbose_name="状态")),
                (
                    "memo",
                    models.TextField(
                        blank=True,
                        default=" ",
                        max_length=200,
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="auto_test_plt.project",
                        verbose_name="测试项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "部署环境",
                "verbose_name_plural": "部署环境",
            },
        ),
    ]
