# Generated by Django 4.2.17 on 2025-09-19 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auto_test_plt", "0004_deployenv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployenv",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="auto_test_plt.project",
                verbose_name="测试环境",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="create_user",
            field=models.ForeignKey(
                db_column="create_user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
    ]
