# Generated by Django 4.2.17 on 2025-09-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auto_test_plt", "0005_alter_deployenv_project_alter_project_create_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Web"),
                    (2, "App"),
                    (3, "API"),
                    (4, "PC"),
                    (5, "功能"),
                    (6, "性能"),
                    (7, "安全"),
                    (8, "硬件"),
                    (9, "音频"),
                    (10, "其它"),
                ],
                default=1,
                verbose_name="项目类型",
            ),
        ),
    ]
