# Generated by Django 4.2.17 on 2025-09-17 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_plt", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "自动化测试", "verbose_name_plural": "自动化测试"},
        ),
        migrations.AddField(
            model_name="project",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="create_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="describe",
            field=models.TextField(
                blank=True, max_length=200, null=True, verbose_name="项目描述"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.BooleanField(default=True, verbose_name="状态"),
        ),
        migrations.AddField(
            model_name="project",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "web"),
                    (2, "app"),
                    (3, "接口"),
                    (4, "功能"),
                    (5, "性能"),
                    (6, "安全"),
                    (7, "硬件"),
                    (8, "其他"),
                ],
                default=1,
                verbose_name="产品类型",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
        ),
        migrations.AddField(
            model_name="project",
            name="version",
            field=models.CharField(default=1, max_length=50, verbose_name="版本"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Jacky测试项目"),
        ),
    ]
