# Generated by Django 4.2.17 on 2025-09-18 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("test_plt", "0002_alter_project_options_project_create_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "缺陷管理", "verbose_name_plural": "缺陷管理"},
        ),
        migrations.RemoveField(
            model_name="project",
            name="create_time",
        ),
        migrations.RemoveField(
            model_name="project",
            name="create_user",
        ),
        migrations.RemoveField(
            model_name="project",
            name="describe",
        ),
        migrations.RemoveField(
            model_name="project",
            name="name",
        ),
        migrations.RemoveField(
            model_name="project",
            name="status",
        ),
        migrations.RemoveField(
            model_name="project",
            name="type",
        ),
        migrations.RemoveField(
            model_name="project",
            name="update_time",
        ),
        migrations.RemoveField(
            model_name="project",
            name="version",
        ),
        migrations.AddField(
            model_name="project",
            name="actual",
            field=models.TextField(
                default=django.utils.timezone.now, verbose_name="实际结果"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="bt_address",
            field=models.TextField(
                default=django.utils.timezone.now, verbose_name="蓝牙地址"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="config",
            field=models.TextField(
                default=django.utils.timezone.now, verbose_name="配置信息"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="日期"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="expect",
            field=models.TextField(default=1, verbose_name="预期结果"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="note",
            field=models.TextField(default=1, verbose_name="备注"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="precondition",
            field=models.TextField(default=1, verbose_name="前置条件"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="recovery",
            field=models.TextField(default=11, verbose_name="复现步骤"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="regression",
            field=models.TextField(default=1, verbose_name="回归测试"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="reporter",
            field=models.TextField(default=1, verbose_name="提交人"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="repro",
            field=models.TextField(default=1, verbose_name="重现概率"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="reviewer",
            field=models.TextField(default=1, verbose_name="评审人"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="step",
            field=models.TextField(default=1, verbose_name="操作步骤"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="summary",
            field=models.TextField(default=1, verbose_name="摘要"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="timestamp",
            field=models.TextField(default=1, verbose_name="时间戳"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="title",
            field=models.TextField(default=1, verbose_name="缺陷标题"),
            preserve_default=False,
        ),
    ]
