# Generated by Django 4.2.17 on 2025-09-18 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("test_plt", "0003_alter_project_options_remove_project_create_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "缺陷/用例", "verbose_name_plural": "缺陷/用例"},
        ),
        migrations.AlterField(
            model_name="project",
            name="actual",
            field=models.CharField(default=" ", max_length=200, verbose_name="实际结果"),
        ),
        migrations.AlterField(
            model_name="project",
            name="bt_address",
            field=models.CharField(default=" ", max_length=100, verbose_name="蓝牙地址"),
        ),
        migrations.AlterField(
            model_name="project",
            name="config",
            field=models.TextField(default=" ", verbose_name="配置信息"),
        ),
        migrations.AlterField(
            model_name="project",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="日期"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="expect",
            field=models.CharField(default=" ", max_length=200, verbose_name="预期结果"),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="主键"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="note",
            field=models.CharField(default=" ", max_length=200, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="project",
            name="precondition",
            field=models.TextField(default=" ", verbose_name="前置条件"),
        ),
        migrations.AlterField(
            model_name="project",
            name="recovery",
            field=models.TextField(default=" ", verbose_name="复现步骤"),
        ),
        migrations.AlterField(
            model_name="project",
            name="regression",
            field=models.TextField(default=" ", verbose_name="回归测试"),
        ),
        migrations.AlterField(
            model_name="project",
            name="reporter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="提交人",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="repro",
            field=models.CharField(default=" ", max_length=50, verbose_name="复现概率"),
        ),
        migrations.AlterField(
            model_name="project",
            name="reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="评审人",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="step",
            field=models.TextField(default=" ", verbose_name="操作步骤"),
        ),
        migrations.AlterField(
            model_name="project",
            name="summary",
            field=models.TextField(default=" ", verbose_name="摘要"),
        ),
        migrations.AlterField(
            model_name="project",
            name="timestamp",
            field=models.CharField(default=" ", max_length=50, verbose_name="时间戳"),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(default=" ", max_length=100, verbose_name="缺陷标题"),
        ),
    ]
