# Generated by Django 4.2.17 on 2025-09-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_plt", "0004_alter_project_options_alter_project_actual_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "缺陷管理", "verbose_name_plural": "缺陷管理"},
        ),
        migrations.AlterField(
            model_name="project",
            name="actual",
            field=models.TextField(default=" ", max_length=200, verbose_name="实际结果"),
        ),
        migrations.AlterField(
            model_name="project",
            name="bt_address",
            field=models.TextField(default=" ", max_length=100, verbose_name="蓝牙地址"),
        ),
        migrations.AlterField(
            model_name="project",
            name="expect",
            field=models.TextField(default=" ", max_length=200, verbose_name="预期结果"),
        ),
        migrations.AlterField(
            model_name="project",
            name="note",
            field=models.TextField(default=" ", max_length=200, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="project",
            name="repro",
            field=models.CharField(default=" ", max_length=100, verbose_name="复现概率"),
        ),
        migrations.AlterField(
            model_name="project",
            name="timestamp",
            field=models.TextField(default=" ", max_length=100, verbose_name="时间戳"),
        ),
    ]
