# Generated by Django 4.2.17 on 2025-09-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_plt", "0005_alter_project_options_alter_project_actual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="module_type",
            field=models.IntegerField(
                choices=[
                    (1, "Web"),
                    (2, "App"),
                    (3, "PC"),
                    (4, "接口"),
                    (5, "功能"),
                    (6, "性能"),
                    (7, "安全"),
                    (8, "硬件"),
                    (9, "音频"),
                    (10, "其它"),
                ],
                default=1,
                verbose_name="测试类型",
            ),
        ),
    ]
