# Generated by Django 4.2.17 on 2025-09-18 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_plt", "0006_project_module_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="module_type",
            new_name="test_type",
        ),
    ]
